"""empty message

Revision ID: 319ef2d56e4e
Revises: 
Create Date: 2023-03-09 00:32:54.653161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319ef2d56e4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profiles',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('property_title', sa.String(length=255), nullable=True),
    sa.Column('property_description', sa.Text(), nullable=True),
    sa.Column('number_room', sa.Integer(), nullable=True),
    sa.Column('number_bathroom', sa.Integer(), nullable=True),
    sa.Column('property_price', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=80), nullable=True),
    sa.Column('property_location', sa.String(length=255), nullable=True),
    sa.Column('property_photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('property_id'),
    sa.UniqueConstraint('property_title')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('property_profiles')
    # ### end Alembic commands ###
